name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Get go dependencies
        run: |
          go get
      - name: Generate test data
        run: |
          make testdata
      - name: Get node dependencies
        run: |
          npm install
        working-directory: integration_tests
      - name: Run unit test
        run: |
          npm install -g typescript
          go test ./...
      - name: Run integration tests
        run: |
          ./scripts/test-ci.sh
        working-directory: integration_tests

  # goreleaser:
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.18
  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v2
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         version: latest
  #         args: release --rm-dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
