name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Run all the tests
        run: |
          npm install -g typescript
          make test
